---------------------------------------------------------
-- GARDEN SEED INVENTORY: TABLE DEFINITIONS
---------------------------------------------------------

-- Drop tables in reverse order of dependencies to avoid FK errors
DROP TABLE Harvest_Data;
DROP TABLE Problem_Data;
DROP TABLE Growth;
DROP TABLE Storage;
DROP TABLE Seed_Order;
DROP TABLE Care;
DROP TABLE Seeds;
DROP TABLE Supplier;

-- Create Core Tables
CREATE TABLE Seeds (
    seed_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    common_name VARCHAR2(50) NOT NULL,
    scientific_name VARCHAR2(50),
    type VARCHAR2(25), -- e.g. 'vegetable', 'flower', 'fruit', 'tree', etc.
    life_cycle VARCHAR2(15), -- e.g. 'annual' or 'perenial'
    characteristics VARCHAR2(100)
);

CREATE TABLE Supplier (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(100),
    supplier_type VARCHAR2(50), -- e.g. 'Commercial' or 'Wild'
    website VARCHAR2(50)
);

-- Create Linking Tables
-- Tells you how to grow that specific seed
CREATE TABLE Care (
    care_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indoor_planting_time DATE,
    outdoor_planting_time DATE,
    transplant_time DATE,
    min_temp NUMBER,
    max_temp NUMBER,
    water_range VARCHAR2(20), -- e.g. 'low', 'high', 'medium'
    sunlight_range VARCHAR2(25), -- e.g. 'bright indirect', 'full shade', etc.
    seed_id NUMBER,  
    CONSTRAINT fk_seed_care
        FOREIGN KEY (seed_id) 
        REFERENCES Seeds(seed_id)
);

-- Connects what was bought from who
CREATE TABLE Seed_Order (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_seed_amount NUMBER,
    order_date DATE,
    price NUMBER(10,2),
    seed_id NUMBER,
    supplier_id NUMBER,
    CONSTRAINT fk_ordered_seed 
        FOREIGN KEY (seed_id) 
        REFERENCES Seeds(seed_id),
    CONSTRAINT fk_order_supplier
        FOREIGN KEY (supplier_id) 
        REFERENCES Supplier(supplier_id)
);

-- Tracks the physical packets of that seed type
CREATE TABLE Storage (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR2(30),
    estimated_expiration DATE,
    seed_aquisition_date DATE,
    seed_id NUMBER,
    CONSTRAINT fk_seed_storage 
        FOREIGN KEY (seed_id) 
        REFERENCES Seeds(seed_id)
);

-- "Main" log for a specific planting session
CREATE TABLE Growth (
    planting_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity_planted NUMBER,
    date_sprouted DATE,
    seed_id NUMBER,
    CONSTRAINT fk_growing_seed
        FOREIGN KEY (seed_id) 
        REFERENCES Seeds(seed_id)
);

-- Create Leaf Tables
-- Links the yield (like "5 lbs of tomatoes") back to that specific growth session
CREATE TABLE Harvest_Data (
    harvest_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_size NUMBER,
    harvest_date DATE,
    planting_location VARCHAR2(50), -- e.g. 'far vegetable' or 'plot 2'
    notes VARCHAR2(100),
    germination_percent NUMBER,
    planting_id NUMBER,
    CONSTRAINT fk_growth_harvest 
        FOREIGN KEY (planting_id) 
        REFERENCES Growth(planting_id)
);

-- Links the pest/disease to the specific plant
CREATE TABLE Problem_Data (
    problem_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_or_pest VARCHAR2(50),
    treatment_or_action VARCHAR2(50),
    outcome VARCHAR2(30),
    observation_date DATE,
    planting_id NUMBER,
    CONSTRAINT fk_growth_problem 
        FOREIGN KEY (planting_id) 
        REFERENCES Growth(planting_id)
);

-- Alter tables for data integrity
ALTER TABLE Harvest_Data 
ADD CONSTRAINT check_germination 
CHECK (germination_percent BETWEEN 0 AND 100);

ALTER TABLE Seeds 
ADD CONSTRAINT check_lifecycle 
CHECK (life_cycle IN ('annual', 'perennial', 'biennial'));
